<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductRealImagesSeeder extends Seeder
{
    public function run()
    {
        // Get parent categories
        $electronics = Category::where('slug', 'consumer-electronics')->first();
        $apparel = Category::where('slug', 'apparel-accessories')->first();
        $auto = Category::where('slug', 'automobiles-motorcycles')->first();
        $home = Category::where('slug', 'home-garden')->first();
        $bags = Category::where('slug', 'luggage-bags-cases')->first();
        $beauty = Category::where('slug', 'beauty-personal-care')->first();
        $sports = Category::where('slug', 'sports-entertainment')->first();
        $jewelry = Category::where('slug', 'jewelry-watches')->first();

        // Real products with actual images from samples folder
        $products = [
            // Electronics - Smartphones
            [
                'name' => 'iPhone 14 Pro Max 256GB',
                'slug' => 'iphone-14-pro-max-256gb',
                'short_description' => 'Latest Apple iPhone with Dynamic Island, 48MP camera',
                'description' => 'The iPhone 14 Pro Max features the new Dynamic Island, always-on display, and the most advanced Pro camera system ever on iPhone.',
                'sku' => 'IPHONE-14-PM-256',
                'price' => 1099.99,
                'stock_quantity' => 25,
                'image' => '/images/samples/H02168b1b1daa4968baaecd90884071e74.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Samsung Galaxy S23 Ultra',
                'slug' => 'samsung-galaxy-s23-ultra',
                'short_description' => '200MP camera, S Pen, 5000mAh battery',
                'description' => 'The Samsung Galaxy S23 Ultra features a 200MP camera, built-in S Pen, and all-day battery life.',
                'sku' => 'SAMSUNG-S23-U',
                'price' => 1199.99,
                'stock_quantity' => 20,
                'image' => '/images/samples/H052cccea2c29460ebabfd23bc16bf3abd.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            // Laptops
            [
                'name' => 'MacBook Pro 14-inch M2 Pro',
                'slug' => 'macbook-pro-14-m2-pro',
                'short_description' => 'Apple M2 Pro chip, 16GB RAM, 512GB SSD',
                'description' => 'Supercharged by the M2 Pro chip, MacBook Pro delivers exceptional performance for professionals.',
                'sku' => 'MACBOOK-14-M2',
                'price' => 1999.99,
                'stock_quantity' => 15,
                'image' => '/images/samples/H0a6003891a1646458251eb8c4dfbfdcd5.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Dell XPS 13 Plus',
                'slug' => 'dell-xps-13-plus',
                'short_description' => 'Intel Core i7, 16GB RAM, OLED display',
                'description' => 'The Dell XPS 13 Plus features a stunning OLED display and powerful Intel performance.',
                'sku' => 'DELL-XPS-13-P',
                'price' => 1499.99,
                'stock_quantity' => 18,
                'image' => '/images/samples/H161f43fc1e47447f93b08c1f0463a1476.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            // Smart Watches
            [
                'name' => 'Apple Watch Series 8',
                'slug' => 'apple-watch-series-8',
                'short_description' => 'Advanced health sensors, always-on Retina display',
                'description' => 'Apple Watch Series 8 features advanced health sensors and innovative safety features.',
                'sku' => 'WATCH-S8-45',
                'price' => 399.99,
                'stock_quantity' => 30,
                'image' => '/images/samples/H21cb8b0f4de44774918fb90ab81dbd040.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Samsung Galaxy Watch 5 Pro',
                'slug' => 'galaxy-watch-5-pro',
                'short_description' => 'Titanium case, GPS route tracking, 590mAh battery',
                'description' => 'The toughest Galaxy Watch yet with titanium case and advanced fitness tracking.',
                'sku' => 'GALAXY-W5-PRO',
                'price' => 449.99,
                'stock_quantity' => 22,
                'image' => '/images/samples/H22f700b3dc9e459991ff1e4899e5df53Y.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            // Headphones
            [
                'name' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'short_description' => 'Industry-leading noise canceling headphones',
                'description' => 'Sony WH-1000XM5 with industry-leading noise cancellation and premium sound quality.',
                'sku' => 'SONY-XM5-BLK',
                'price' => 348.00,
                'stock_quantity' => 35,
                'image' => '/images/samples/H275df7ef27b64f48be20a18069d15d74o.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'AirPods Pro 2nd Gen',
                'slug' => 'airpods-pro-2',
                'short_description' => 'Active Noise Cancellation, Adaptive Transparency',
                'description' => 'AirPods Pro (2nd generation) with up to 2x more Active Noise Cancellation.',
                'sku' => 'AIRPODS-PRO-2',
                'price' => 249.00,
                'stock_quantity' => 40,
                'image' => '/images/samples/H37349e7735694dc3b8c0bec68ebe5fd3I.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            // Apparel - Wedding Dresses
            [
                'name' => 'Elegant Lace Wedding Dress',
                'slug' => 'elegant-lace-wedding-dress',
                'short_description' => 'A-line silhouette, vintage lace, long train',
                'description' => 'Beautiful lace wedding dress with A-line silhouette and vintage-inspired design.',
                'sku' => 'WD-LACE-001',
                'price' => 899.99,
                'stock_quantity' => 12,
                'image' => '/images/samples/H3f05ccb909ee4648b9e8389e3bfba1c6S.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $apparel?->id,
            ],
            [
                'name' => 'Mermaid Wedding Gown',
                'slug' => 'mermaid-wedding-gown',
                'short_description' => 'Satin fabric, crystal embellishments, sweetheart neckline',
                'description' => 'Stunning mermaid wedding gown with crystal details and dramatic train.',
                'sku' => 'WD-MERMAID-002',
                'price' => 1299.99,
                'stock_quantity' => 8,
                'image' => '/images/samples/H40bdc1f090f24847be56d531f686836cL.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $apparel?->id,
            ],
            // Evening Dresses
            [
                'name' => 'Sequin Evening Gown',
                'slug' => 'sequin-evening-gown',
                'short_description' => 'Full sequin, floor-length, multiple colors',
                'description' => 'Dazzling sequin evening gown perfect for formal events and galas.',
                'sku' => 'ED-SEQUIN-001',
                'price' => 349.99,
                'stock_quantity' => 20,
                'image' => '/images/samples/H460b614033394b0e86b48ad3e250c974S.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $apparel?->id,
            ],
            [
                'name' => 'Velvet Evening Dress',
                'slug' => 'velvet-evening-dress',
                'short_description' => 'Luxurious velvet, off-shoulder design',
                'description' => 'Elegant velvet evening dress with off-shoulder neckline and fitted silhouette.',
                'sku' => 'ED-VELVET-002',
                'price' => 279.99,
                'stock_quantity' => 15,
                'image' => '/images/samples/H4b9a913540e847a3b4ae512489c54950e.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $apparel?->id,
            ],
            // Handbags
            [
                'name' => 'Designer Leather Handbag',
                'slug' => 'designer-leather-handbag',
                'short_description' => 'Genuine leather, gold hardware, multiple compartments',
                'description' => 'Premium leather handbag with elegant design and practical organization.',
                'sku' => 'BAG-LEATHER-001',
                'price' => 189.99,
                'stock_quantity' => 25,
                'image' => '/images/samples/H4df39b980b484bdbb6573a3de3dfed08r.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $bags?->id,
            ],
            [
                'name' => 'Quilted Chain Shoulder Bag',
                'slug' => 'quilted-chain-bag',
                'short_description' => 'Classic quilted pattern, chain strap, PU leather',
                'description' => 'Stylish quilted shoulder bag with signature chain strap and elegant design.',
                'sku' => 'BAG-QUILT-002',
                'price' => 79.99,
                'stock_quantity' => 40,
                'image' => '/images/samples/H5d078e8ae06b457f9c41e73ec0eb69ba0.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $bags?->id,
            ],
            // Watches
            [
                'name' => 'Luxury Automatic Watch',
                'slug' => 'luxury-automatic-watch',
                'short_description' => 'Sapphire crystal, stainless steel, water-resistant',
                'description' => 'Premium automatic watch with sapphire crystal and genuine leather strap.',
                'sku' => 'WATCH-AUTO-001',
                'price' => 299.99,
                'stock_quantity' => 18,
                'image' => '/images/samples/H608dcb62f3474e3a911a6db4710ca7f9G.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $jewelry?->id,
            ],
            [
                'name' => 'Minimalist Quartz Watch',
                'slug' => 'minimalist-quartz-watch',
                'short_description' => 'Simple design, mesh band, waterproof',
                'description' => 'Elegant minimalist watch with mesh stainless steel band and clean dial.',
                'sku' => 'WATCH-MIN-002',
                'price' => 89.99,
                'stock_quantity' => 30,
                'image' => '/images/samples/H61878cba3a314d5d8f1b5b5f33de4697b.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $jewelry?->id,
            ],
            // Home - Furniture
            [
                'name' => 'Modern Velvet Sofa',
                'slug' => 'modern-velvet-sofa',
                'short_description' => '3-seater, premium velvet, solid wood legs',
                'description' => 'Stylish velvet sofa with modern design and comfortable cushioning.',
                'sku' => 'SOFA-VELVET-001',
                'price' => 699.99,
                'stock_quantity' => 10,
                'image' => '/images/samples/H6fbde8318bab4462aa44e3220a920c292.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $home?->id,
            ],
            [
                'name' => 'Ergonomic Office Chair',
                'slug' => 'ergonomic-office-chair',
                'short_description' => 'Lumbar support, adjustable height, breathable mesh',
                'description' => 'Professional ergonomic office chair with full adjustable features.',
                'sku' => 'CHAIR-ERG-002',
                'price' => 349.99,
                'stock_quantity' => 22,
                'image' => '/images/samples/H86f28195a2254257b9d5a17067130646Z.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $home?->id,
            ],
            // Beauty
            [
                'name' => 'Professional Makeup Brush Set',
                'slug' => 'pro-makeup-brush-set',
                'short_description' => '15 pieces, synthetic bristles, leather case',
                'description' => 'Complete professional makeup brush set with soft synthetic bristles.',
                'sku' => 'BEAUTY-BRUSH-001',
                'price' => 45.99,
                'stock_quantity' => 50,
                'image' => '/images/samples/H8b6e067bb8574726b4bd6806385e35f9k.png',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $beauty?->id,
            ],
            [
                'name' => 'Anti-Aging Skincare Kit',
                'slug' => 'anti-aging-skincare-kit',
                'short_description' => 'Serum, moisturizer, eye cream, 3-piece set',
                'description' => 'Complete anti-aging skincare regimen with clinically proven ingredients.',
                'sku' => 'BEAUTY-KIT-002',
                'price' => 129.99,
                'stock_quantity' => 35,
                'image' => '/images/samples/H8baa69a03d9c46e68b01c8d481044eb6f.png',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $beauty?->id,
            ],
            // Sports
            [
                'name' => 'Yoga Mat Premium',
                'slug' => 'yoga-mat-premium',
                'short_description' => '6mm thick, non-slip, carrying strap included',
                'description' => 'High-density yoga mat with excellent cushioning and non-slip surface.',
                'sku' => 'SPORT-YOGA-001',
                'price' => 39.99,
                'stock_quantity' => 60,
                'image' => '/images/samples/H8e3a2028d0284d519b815caa66ee8813r.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $sports?->id,
            ],
            [
                'name' => 'Adjustable Dumbbell Set',
                'slug' => 'adjustable-dumbbell-set',
                'short_description' => '5-25kg adjustable, space-saving design',
                'description' => 'Quick-adjust dumbbell system replaces 15 sets of weights.',
                'sku' => 'SPORT-DB-002',
                'price' => 299.99,
                'stock_quantity' => 20,
                'image' => '/images/samples/H9b3243b35aae468eb6d8c7923bea31e5Q.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $sports?->id,
            ],
            // More Electronics
            [
                'name' => 'iPad Pro 12.9-inch M2',
                'slug' => 'ipad-pro-12-m2',
                'short_description' => 'Liquid Retina XDR display, Apple M2 chip, 128GB',
                'description' => 'The ultimate iPad experience with M2 chip and stunning XDR display.',
                'sku' => 'IPAD-PRO-12-M2',
                'price' => 1099.00,
                'stock_quantity' => 15,
                'image' => '/images/samples/H9ffbfa9ddebe44fdae9ffd2e616e5a8eA.jpg',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Sony PlayStation 5',
                'slug' => 'sony-playstation-5',
                'short_description' => '4K gaming, 825GB SSD, DualSense controller',
                'description' => 'Experience lightning-fast loading and immersive gaming with PS5.',
                'sku' => 'PS5-STD-001',
                'price' => 499.99,
                'stock_quantity' => 8,
                'image' => '/images/samples/HTB11adWdkfb_uJkSndV761BkpXaL.png',
                'is_featured' => true,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            // More Apparel
            [
                'name' => 'Men\'s Slim Fit Suit',
                'slug' => 'mens-slim-fit-suit',
                'short_description' => 'Two-piece, navy blue, modern fit',
                'description' => 'Professional slim fit suit perfect for business and formal occasions.',
                'sku' => 'SUIT-NAVY-001',
                'price' => 249.99,
                'stock_quantity' => 18,
                'image' => '/images/samples/Ha1ca39b7ef9a4b1bab90dfdbbfd4cdf6T.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $apparel?->id,
            ],
            [
                'name' => 'Summer Floral Dress',
                'slug' => 'summer-floral-dress',
                'short_description' => 'Lightweight, sundress, multiple sizes',
                'description' => 'Beautiful floral summer dress with comfortable fit and breathable fabric.',
                'sku' => 'DRESS-SUMMER-002',
                'price' => 59.99,
                'stock_quantity' => 45,
                'image' => '/images/samples/Ha2f8d1f629634d43b3477b35ff9daca1U.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $apparel?->id,
            ],
            // Auto Accessories
            [
                'name' => 'Car Dashboard Camera',
                'slug' => 'car-dashboard-camera',
                'short_description' => '4K recording, 170° wide angle, night vision',
                'description' => 'Premium dash cam with 4K resolution and advanced driver assistance.',
                'sku' => 'AUTO-CAM-001',
                'price' => 129.99,
                'stock_quantity' => 30,
                'image' => '/images/samples/Ha37bb822a2cd41d69d759aa842531070w.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $auto?->id,
            ],
            [
                'name' => 'Wireless Car Charger Mount',
                'slug' => 'wireless-car-charger',
                'short_description' => '15W fast charge, auto-clamp, air vent mount',
                'description' => 'Convenient wireless charging car mount with automatic phone clamping.',
                'sku' => 'AUTO-CHARGE-002',
                'price' => 34.99,
                'stock_quantity' => 50,
                'image' => '/images/samples/Hb54c59a50b8b4e5d8c10336d2a04faccw.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $auto?->id,
            ],
            // Home Decor
            [
                'name' => 'Modern Table Lamp',
                'slug' => 'modern-table-lamp',
                'short_description' => 'LED, touch control, 3 color temperatures',
                'description' => 'Stylish modern table lamp with adjustable brightness and color temperature.',
                'sku' => 'LAMP-MODERN-001',
                'price' => 49.99,
                'stock_quantity' => 40,
                'image' => '/images/samples/Hb8d481a0ec2e4779be411159a64d5f3bg.png',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $home?->id,
            ],
            [
                'name' => 'Decorative Wall Art Set',
                'slug' => 'wall-art-set',
                'short_description' => '3 pieces, abstract design, canvas print',
                'description' => 'Beautiful 3-piece wall art set to enhance any living space.',
                'sku' => 'ART-SET-002',
                'price' => 79.99,
                'stock_quantity' => 25,
                'image' => '/images/samples/Hb988d4c8cee547f2bc614ebdea8ebc16k.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $home?->id,
            ],
            // Jewelry
            [
                'name' => '925 Silver Necklace',
                'slug' => 'silver-necklace-925',
                'short_description' => 'Sterling silver, pendant included, 18-inch chain',
                'description' => 'Elegant 925 sterling silver necklace with beautiful pendant design.',
                'sku' => 'JEWEL-Necklace-001',
                'price' => 89.99,
                'stock_quantity' => 35,
                'image' => '/images/samples/Hc8d21612ea5f442a8207a772f358be71o.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $jewelry?->id,
            ],
            // More products...
            [
                'name' => 'Portable Bluetooth Speaker',
                'slug' => 'portable-bluetooth-speaker',
                'short_description' => 'Waterproof, 20W, 12-hour battery',
                'description' => 'Rugged portable speaker with powerful sound and waterproof design.',
                'sku' => 'SPK-BT-001',
                'price' => 59.99,
                'stock_quantity' => 55,
                'image' => '/images/samples/Hd237bc4dc96e4d2fa1a47dcd0a61b4d1T.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Stainless Steel Water Bottle',
                'slug' => 'steel-water-bottle',
                'short_description' => 'Insulated, 1L capacity, keeps cold 24hrs',
                'description' => 'Premium insulated water bottle perfect for sports and outdoor activities.',
                'sku' => 'BOTTLE-1L-002',
                'price' => 24.99,
                'stock_quantity' => 80,
                'image' => '/images/samples/Hd4ce009d6da04e8db5d0e123ada1d149f.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $sports?->id,
            ],
            [
                'name' => 'Leather Travel Wallet',
                'slug' => 'leather-travel-wallet',
                'short_description' => 'RFID blocking, passport holder, multiple slots',
                'description' => 'Premium leather travel wallet with RFID protection and passport holder.',
                'sku' => 'WALLET-TRAVEL-001',
                'price' => 39.99,
                'stock_quantity' => 40,
                'image' => '/images/samples/He57a6e155d0b49868aacfc05c52a7d29U.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $bags?->id,
            ],
            [
                'name' => 'Kitchen Knife Set',
                'slug' => 'kitchen-knife-set',
                'short_description' => '5 pieces, stainless steel, wooden block',
                'description' => 'Professional kitchen knife set with sharp blades and ergonomic handles.',
                'sku' => 'KNIFE-SET-002',
                'price' => 69.99,
                'stock_quantity' => 30,
                'image' => '/images/samples/Hf49b5d5456714977b8df92ffaa2e379fW.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $home?->id,
            ],
            [
                'name' => 'Gaming Mechanical Keyboard',
                'slug' => 'gaming-mechanical-keyboard',
                'short_description' => 'RGB backlight, blue switches, anti-ghosting',
                'description' => 'Professional gaming keyboard with tactile mechanical switches.',
                'sku' => 'KB-GAME-001',
                'price' => 79.99,
                'stock_quantity' => 25,
                'image' => '/images/samples/Hf4de7f4419a34fc38321bf38bc126cd6R.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Wireless Gaming Mouse',
                'slug' => 'wireless-gaming-mouse',
                'short_description' => '16K DPI, RGB lights, rechargeable',
                'description' => 'High-precision wireless gaming mouse with customizable RGB lighting.',
                'sku' => 'MOUSE-GAME-002',
                'price' => 49.99,
                'stock_quantity' => 35,
                'image' => '/images/samples/Hf6a670bc907b459fb008bbf1362c5c6fP.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $electronics?->id,
            ],
            [
                'name' => 'Ceramic Dinnerware Set',
                'slug' => 'ceramic-dinnerware-set',
                'short_description' => '16 pieces, microwave safe, modern design',
                'description' => 'Complete ceramic dinnerware set for 4 people with contemporary design.',
                'sku' => 'PLATE-SET-001',
                'price' => 89.99,
                'stock_quantity' => 20,
                'image' => '/images/samples/Hf9951c09b2c645438949c783ffd0d54aT.jpg',
                'is_featured' => false,
                'is_active' => true,
                'category_id' => $home?->id,
            ],
        ];

        foreach ($products as $product) {
            if ($product['category_id']) {
                Product::create($product);
            }
        }

        $this->command->info('Created ' . count($products) . ' products with real images!');
    }
}
